spring:
  application:
    name: 14-sprint-mission
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true          # SQL 줄바꿈 포맷팅
        highlight_sql: true       # SQL 색깔 강조
        use_sql_comments: true    # 주석 표시
  sql:
    init:
      mode: NEVER
      schema-locations:
        - 'classpath:schema.sql'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54322/discodeit?useSSL=false
    username: discodeit_user
    password: discodeit1234

logging:
  level:
    org.hibernate.SQL: DEBUG              # 실행되는 SQL 쿼리 로그
    org.hibernate.orm.jdbc.bind: TRACE    # 바인딩 파라미터 값 로그 (Hibernate 6+)
server:
  port: 8080

discodeit:
  repository:
    type: jcf # jcf | file
    file-directory: .discodeit

file:
  path: .uploader